export default function Head() {
  return (
    <>
      <title>Sarvnaz Kasaei</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="data:image/svg+xml,<><text y=%22.9em%22 font-size=%2290%22>👋</text></svg>"
      />
    </>
  );
}